services:
  db:
    image: postgres:15
    container_name: feedback360_postgres_new
    restart: always
    environment:
      POSTGRES_USER: feedback_user
      POSTGRES_PASSWORD: feedback123456
      POSTGRES_DB: feedback360_db
    ports:
      - '5433:5432'
    volumes:
      - feedback360_new_data:/var/lib/postgresql/data
    networks:
      - feedback360_network

networks:
  feedback360_network:
    driver: bridge

volumes:
  feedback360_new_data:
